name: Working Releases
on:
  push:
    tags:
      - "v*"
    branches:
      -main
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.2.x'
          channel: stable

      - name: Download Dependencies
        run: flutter pub get

      - name: Testing
        run: flutter test

      - name: Building apk
        run: flutter build apk
        
      - name: Automatic Releases
        uses: marvinpinto/action-automatic-releases
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          files: "build/app/outputs/flutter-apk/*"


