name: Deploy to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      -main

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.2.x'
          channel: stable

      - name: Download Dependencies
        run: flutter pub get

      - name: Testing
        run: flutter test

      - name: Building apk
        run: flutter build apk

      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/flutter-apk/*"
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}
